global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System.Runtime.InteropServices;
global using System.Threading;
global using Avalonia;
global using Avalonia.Controls;
global using Avalonia.Controls.Primitives;
// Import only the shape types we use so System.IO.Path stays unambiguous
global using Ellipse   = Avalonia.Controls.Shapes.Ellipse;
global using Rectangle = Avalonia.Controls.Shapes.Rectangle;
global using Avalonia.Input;
global using Avalonia.Interactivity;
global using Avalonia.Layout;
global using Avalonia.Media;
global using Avalonia.Platform;
global using Avalonia.Threading;
global using Avalonia.Styling;
global using Newtonsoft.Json;
global using GamingEqualizer.Models;
global using GamingEqualizer.Platform;
